# Generated by Django 3.2.8 on 2021-12-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discription',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
