# Generated by Django 3.2.8 on 2021-12-29 19:30

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_posts_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(default='Default-Profile-Picture-Download-PNG-Image.png', upload_to=home.models.profile_upload_location),
        ),
    ]
