# Generated by Django 3.2.8 on 2022-01-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
